### ISSUE TITLE
Clarify host / build dependencies

### ISSUE THREAD

**Issue by m-kuhn** [open-vcpkg/python-registry#7]
[vcpkg-python-scripts](https://github.com/open-vcpkg/vcpkg-python/tree/main/ports/vcpkg-python-scripts) offers nice helpers to build python packages (thanks to @Neumann-A), this is included as a host dependency. The build dependencies it relies on must be available to the build process on the target. Should all ports declare these build dependencies explicitly? Do we separate runtime/build dependencies somehow? Should venv's play a role for build dependencies. No clear picture yet ...

**Comment by Neumann-A** [comment]
All dependencies need to be declared. This includes runtime deps so that `import * from <PORT>` works as expected without additional work. 
Be aware that I did not take care to properly differentiate between host/target. 

> Should venv's play a role for build dependencies.

Could be done but I don't see a benefit for it. Often you'll just redownload the same stuff again instead of taking a simple dependency on it.  E.g. all the python build extensions could be in venv but they are reused so often it is hardly worth the effort.

**Comment by m-kuhn** [comment]
So the following dependency declaration will be in almost every port (next to all the other dependencies)

```
    "py-setuptools",
    {
      "name": "vcpkg-python-scripts",
      "host": true
    }
```

**Comment by Neumann-A** [comment]
Yes it is the same as e.g. vcpkg-cmake. 

Should probably be:
```
    {
      "name": "py-setuptools",
      "host": true
    },
    {
      "name": "vcpkg-python-scripts",
      "host": true
    }
```

since setuptools is probably a build requirement for the host python and not for the target.

**Comment by m-kuhn** [comment]
Thinking about it this way, the picture becomes clearer.
Do you think it would make sense to let `vcpkg-python-scripts` depend on `py-setuptools` for ease of use?
