### ISSUE TITLE
add_dll_directory

### ISSUE THREAD

**Issue by m-kuhn** [open-vcpkg/python-registry#8]
To load deps, python needs `add_dll_directory()` calls. At the moment, python cannot import any of the libraries.
[Patching individual ports](https://github.com/open-vcpkg/vcpkg-python/blob/main/ports/py-sip/add_dll_directory.patch) doesn't seem to be the way to happiness. Should the `python3` port be patched to add the main library directory on load? Should another utility port be added that adds this to the python path ([`sitecustomize`](https://docs.python.org/3/library/site.html#module-sitecustomize) or similar)?

**Comment by Neumann-A** [comment]
> At the moment, python cannot import any of the libraries.
[Patching individual ports](https://github.com/open-vcpkg/vcpkg-python/blob/main/ports/py-sip/add_dll_directory.patch) doesn't seem to be the way to happiness.

It also breaks embedding since the files become impossible to relocate. 

> Should the python3 port be patched to add the main library directory on load

I already have a patch (actual two) in my python overlay derived from conda.

**Comment by m-kuhn** [comment]
> > Should the python3 port be patched to add the main library directory on load
> 
> I already have a patch (actual two) in my python overlay derived from conda.

Nice, are you planning to port these or would you like me to do so?
